# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: v3.32.0
components:
  libcalico-go:
    version: v3.32.0
  typha:
    version: v3.32.0
  node:
    version: v3.32.0
  cni:
    version: v3.32.0
  node-windows:
    version: v3.32.0
  cni-windows:
    version: v3.32.0
  kube-controllers:
    version: v3.32.0
  goldmane:
    version: v3.32.0
  flexvol:
    version: v3.32.0
  apiserver:
    version: v3.32.0
  csi:
    version: v3.32.0
  csi-node-driver-registrar:
    version: v3.32.0
  key-cert-provisioner:
    version: v3.32.0
  whisker:
    version: v3.32.0
  whisker-backend:
    version: v3.32.0
  envoy-gateway:
    version: v3.32.0
  envoy-proxy:
    version: v3.32.0
  envoy-ratelimit:
    version: v3.32.0
  guardian:
    version: v3.32.0
